import {
  Bot,
  Brain,
  Shield,
  Wrench,
  Dumbbell,
  DollarSign,
  TrendingUp,
  Search,
  Music,
  Plane,
  ShoppingCart,
  Trophy,
  Megaphone,
  Mail,
  Calendar,
  Video,
  BookOpen,
  FileText,
  BarChart3,
  Database,
  Image,
  Heart,
  Film,
  Scissors,
  Package,
  LineChart,
  PieChart,
} from "lucide-react";

export const AGENT_ICONS: Record<string, React.ElementType> = {
  Harv: Bot,
  Router: Brain,
  Guardian: Shield,
  Medic: Wrench,
  Fitness: Dumbbell,
  Finance: DollarSign,
  Trading: TrendingUp,
  Research: Search,
  Music: Music,
  Travel: Plane,
  Shopping: ShoppingCart,
  Sports: Trophy,
  "Auto Marketing": Megaphone,
  Email: Mail,
  Scheduler: Calendar,
  "Video Digest": Video,
  "YouTube Digest": Video,
  "TikTok Digest": Video,
  "Twitter Digest": Video,
  Learning: BookOpen,
  Journal: FileText,
  Analytics: BarChart3,
  Memory: Database,
  Ledger: FileText,
  Drive: Database,
  "Image Gen": Image,
  Heartbeat: Heart,
  Postman: Mail,
  "Media Manager": Film,
  "Video Gen": Film,
  "Video Editor": Scissors,
  "Product Research": Package,
  "Market Research": LineChart,
  "Data Viz": PieChart,
};
